### ISSUE TITLE
Next time deployment

### ISSUE THREAD

**Issue by JPMallow** [ubergeek42/domjudge-aws#2]
Hi,

We are customising the domjudge admin panel & user flow. Is this still possible to use this library?

Thanks

**Comment by ubergeek42** [comment]
Yes. You'll need to edit the prepare.sh[1] script to point to your own git repository(or edit it and use a local folder or something similar).

You also need to make sure that your edits do not conflict with some of the patches that are made by that script, notably these bits:
https://github.com/ubergeek42/domjudge-aws/blob/master/prepare.sh#L72 - Database patching to use RDS
https://github.com/ubergeek42/domjudge-aws/blob/master/prepare.sh#L75 - session handling to use dynamodb shared between webservers

Let me know if you have any other questions about this.

[1] - https://github.com/ubergeek42/domjudge-aws/blob/master/prepare.sh#L14

**Comment by JPMallow** [comment]
Hi

Thanks for your clarification.

Let say we are doing hosting as per the documentation which you mentioned. From next time, how can I deploy my new code as we will improve the features periodically? Basically what we require is, from which step I should start / is there any new steps for this for continuous delivery?

**Comment by ubergeek42** [comment]
To deploy new versions of your domjudge package, you would run the prepare.sh script again. That'll give you a new domjudge archive. You edit the terraform config to point at the new archive, and that'll do the update.

You'll also need to destroy any existing webservers so that new ones will launch with the correct configuration. Alternatively you could log into one of the webservers and run the deploy script as root(There is a script in root's home directory). You'd need to edit the env_vars file(or whatever it's actually named) to point to the new archive file you created with the prepare.sh script.

I have some things in the works to make this process better, but nothing published yet.
